src/Entity/Topic.php
<?php

namespace App\Entity;

use App\Repository\TopicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TopicRepository::class)
 */
class Topic
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="topics")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="boolean")
     */
    private $solved;

    /**
     * @ORM\Column(type="boolean")
     */
    private $closed;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="topic", orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "ASC"})
     */
    private $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->solved = false;
        $this->closed = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSolved(): ?bool
    {
        return $this->solved;
    }

    public function setSolved(bool $solved): self
    {
        $this->solved = $solved;

        return $this;
    }

    public function getClosed(): ?bool
    {
        return $this->closed;
    }

    public function setClosed(bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setTopic($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getTopic() === $this) {
                $post->setTopic(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->title;
    }

    public function getInfos() {
        return "By ".$this->author." at ".$this->createdAt->format("d-m-Y H:i");
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\Topic;
use App\Form\PostType;
use App\Form\TopicType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @IsGranted("ROLE_USER")
 */
class ForumController extends AbstractController
{

    // * GESTION DES TOPICS
    /**
     * @Route("topic/add", name="topic_add")
     */
    public function addTopic(Request $request, Topic $topic = null) {

        $topic = new Topic();
        $form = $this->createForm(TopicType::class, $topic);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $topic = $form->getData();
            $topic->setAuthor($this->getUser());
           
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($topic);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render("forum/topic_add.html.twig", [
            "topic" => $topic,
            "form_addTopic" => $form->createView()
        ]);
    }

    /**
     * @Route("/topic/{id}/delete", name="topic_delete")
     */
    public function deleteTopic(Topic $topic = null) {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($topic);
        $entityManager->flush();
        return $this->redirectToRoute('home');
    }

    /**
     * @Route("/topic/close/{id}", name="topic_close")
     */
    public function closeTopic(Topic $topic): Response {

        $topic->setClosed($topic->getClosed() ? false : true);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return $this->redirectToRoute('home');

        // return new JsonResponse($topic->getClosed());

        /* 
            $encoders = [new XmlEncoder(), new JsonEncoder()];
            $normolizers = [new ObjectNormalizer()],
            $serializer = new Serializer($normalizers, $encoders),
            $json = $serializer->serialize($topic, 'json')

            return new JsonResponse($json); 

        */
    }

    /**
     * @Route("/topic/solve/{id}", name="topic_solve")
     */
    public function solveTopic(Topic $topic): Response {

        $topic->setSolved(true);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return $this->redirectToRoute('home');
    }

    /**
     * @Route("/topic/unsolve/{id}", name="topic_unsolve")
     */
    public function unsolveTopic(Topic $topic): Response {

        $topic->setSolved(false);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return $this->redirectToRoute('home');
    }

    // * GESTION DES POSTS
    /**
     * @Route("/topic/{id}", name="posts")
     */
    public function posts(Request $request, Topic $topic) {

        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        $form->remove('cancel');
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post = $form->getData();
                
            $post->setAuthor($this->getUser());
            $post->setTopic($topic);
    
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();
    
            return $this->redirectToRoute('posts', ['id' => $topic->getId()]);
        }

        return $this->render("forum/posts.html.twig", [
            "topic" => $topic,
            "form_addPost" => $form->createView()
        ]);
    }

    /**
     * @Route("/post/{id}/delete", name="post_delete")
     */
    public function deletePost(Post $post) {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($post);
        $entityManager->flush();
        return $this->redirectToRoute('posts', ['id' => $post->getTopic()->getId()]);
    }

    /**
     * @Route("/post/{id}", name="post_edit")
     */
    public function editPost(Request $request, Post $post) {

        $form = $this->createForm(PostType::class, $post);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post = $form->getData();
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();
    
            return $this->redirectToRoute('posts', ['id' => $post->getTopic()->getId()]);
        }

        if($this->getUser() === $post->getAuthor()){
            return $this->render("forum/post_edit.html.twig", [
                "post" => $post,
                "form_editPost" => $form->createView()
            ]);
        } else {
            return $this->redirectToRoute("home");
        }
    }
}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}

{% endblock %}

templates/forum/post_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit post{% endblock %}

{% block body %}

<h1>Edit post</h1>

<div>
    {{ form_start(form_editPost) }}
        {{ form_widget(form_editPost.message) }}
        <div>
            {{ form_widget(form_editPost.reply) }} <a href="{{ path('posts', {'id':post.topic.id}) }}">{{ form_widget(form_editPost.cancel) }}</a>
        </div>
    {{ form_end(form_editPost) }}
</div>

{% endblock %}

templates/forum/posts.html.twig
{% extends 'base.html.twig' %}

{% block title %}TOPIC | {{ topic }}{% endblock %}

{% block body %}

<h1 class="mb-0">{{ topic }}
        {% if topic.solved %}
            <span class="uk-badge uk-badge-success">Solved</span>
        {% endif %}
        {% if topic.closed %}
            <span class="uk-badge uk-badge-warning">Closed</span>
        {% endif %}

        {% if topic.author.id == app.user.id %}
            {% if topic.solved %}
                <a class="uk-badge uk-badge-warning" href="">Mark as unresolved</a>
            {% else %}
                <a class="uk-badge uk-badge-success" href="">Mark as resolved</a>
            {% endif %}
            
            {% if topic.closed %}
                <a class="uk-badge uk-badge-success" href="">Open topic</a>
            {% else %}
                <a class="uk-badge uk-badge-warning" href="">Close topic</a>
            {% endif %}
        {% endif %}
</h1>

<p class="mt-0"><img class="avatar-small" src="{{ topic.author.avatar }}" alt=""> {{ topic.infos }}</p>
<span uk-icon="icon: chevron-left"></span><a href="{{ path('home') }}">Back to the topics</a>

<h2>Posts <span class="uk-badge uk-badge-gray">{{ topic.posts | length }}</span></h2>

<table id="posts" class="uk-table uk-table-striped uk-table-responsive">
    <thead>
        <tr>
            <th>FROM / AT</th>
            <th>MESSAGE</th>
            <th>ACTIONS</th>
        </tr>
    </thead>
    <tbody>
        {% for post in topic.posts %}
            <tr>
                <td class="fixed dotted">
                    <div class="main-author">
                        <div><img class="avatar" src="{{ post.author.avatar }}" alt=""></div>
                        <div>
                            <a href="{{ path('user_show', {'id':post.author.id}) }}">{{ post.author }}</a> <br>
                            <span class="small-font">{{ post.createdAt | date('d-m-Y H:i') }}</span> <br>
                            <span class="small-font">Posts : {{ post.author.posts | length }}</span> - 
                            <span class="small-font">Topics : {{ post.author.topics | length }}</span>
                        </div>
                    </div>
                </td>
                <td class="message">
                    <div class="message-content">
                        <div>{{ post.message | raw }}</div>
                        <div>#{{ post.id }}</div>
                    </div>
                </td>
                <td class="fixed">
                    {% if app.user and app.user == post.author %}
                        <a class="warning" href="{{ path('post_edit', {'id':post.id}) }}" uk-icon="icon: file-edit"></a> <a class="danger" href="{{ path('post_delete', {'id': post.id}) }}" uk-icon="icon: trash"></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% if app.user %}
    <h3><span uk-icon="icon: reply; ratio: 1.2"></span> Post a Reply</h3>
    <div>
        {% if topic.closed == false %}
            {{ form_start(form_addPost, {'attr': {'novalidate': 'novalidate'}}) }}
                {{ form_errors(form_addPost) }}
                {{ form_widget(form_addPost.message) }}
                {{ form_widget(form_addPost.reply) }}
            {{ form_end(form_addPost) }}
        {% else %}
            <span class="uk-badge uk-badge-warning">Topic is closed !</span>
        {% endif %}
    </div>
{% endif %}

{% endblock %}

templates/forum/topic_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ topic }}{% endblock %}

{% block body %}

<h1>Add topic</h1>

<div>
    {{ form_start(form_addTopic) }}
        {{ form_widget(form_addTopic.title) }}
        <div>
            {{ form_widget(form_addTopic.add_topic) }} <a href="{{ path('home') }}">{{ form_widget(form_addTopic.cancel) }}</a>
        </div>
    {{ form_end(form_addTopic) }}
</div>

{% endblock %}